name: Reproduce `eza` bug

on: push

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
       os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download and extract `eza` v0.23.0
        if: runner.os == 'Linux'
        run: |
          curl --location --output eza.tar.gz https://github.com/eza-community/eza/releases/download/v0.23.0/eza_x86_64-unknown-linux-gnu.tar.gz
          tar xf eza.tar.gz

      - name: Install rust
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@stable

      - name: Clone `eza` repo
        if: runner.os == 'macOS'
        uses: actions/checkout@main
        with:
          repository: 'eza-community/eza'

      - name: Build `eza`
        if: runner.os == 'macOS'
        run: |
          cargo build --release
          ln -sf target/release/eza .

      - name: Populate current directory
        run: |
          touch foo bar baz
          mkdir hello goodbye

      - name: Run `ls` on current directory
        run: |
          echo '## `ls -la` output' >>"${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
          ls -la | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"

      - name: Run `eza` on current directory
        run: |
          echo '## `./eza -la` output' >>"${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
          ./eza -la | tee -a "${GITHUB_STEP_SUMMARY}"
          echo '```' >>"${GITHUB_STEP_SUMMARY}"
          ./eza -la
